---
  - name: 作業用ユーザ作成
    user:
      name: "{{ work_usr }}"
      shell: /bin/bash
      state: present
    ignore_errors: yes

  - name: 作業ディレクトリ作成
    file:
      path: "{{ work_dir }}"
      state: directory
      owner: websrv
      group: websrv
      mode: 755
    ignore_errors: yes

  - name: SELinux無効化
    replace:
      path: /etc/selinux/config
      regexp: '^SELINUX=enforcing'
      replace: SELINUX=disabled
      backup: yes
    ignore_errors: yes
