---
  - name: 公開用ディレクトリを作成
    file:
      path: /var/www/websrv
      state: directory
      owner: websrv
      group: websrv
      mode: 755
    ignore_errors: yes

  - name: topページ（index.html）を公開ディレクトリに配置
    copy:
      src: roles/nginx/file/index.html
      dest: /var/www/websrv
    ignore_errors: yes

  - name: 公開ディレクトリの権限を変更
    shell: chown -R websrv:websrv /var/www/websrv
    ignore_errors: yes

  - name: default.confを転送
    copy:
      src: roles/nginx/file/default.conf
      dest: /etc/nginx/conf.d/default.conf
      mode: 644
    ignore_errors: yes

  - name: default.confのbackup
    shell: cp -p /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf_$(date +%Y%m%d)_$(hostname) && ls -lh $_
    ignore_errors: yes

  - name: default.confの設定(listen-port指定)
    shell: sed -i -e "s/ip-add:80/$(hostname -I |awk '{print $1}'):80/g" /etc/nginx/conf.d/default.conf
    ignore_errors: yes


