---
  - name: httpdが存在しているかの確認
    stat:
      path: "/usr/lib/systemd/system/{{ stop_process }}"
    register: service_status

  - name: 実行結果（httpd存在性）
    debug:
      msg: "{{ service_status }}"

  - name: httpdが存在している場合はサービスを停止
    systemd:
      name: "{{ stop_process }}"
      state: stopped
      enabled: no
    when: service_status.stat.exists
    register: stop_process_result
    ignore_errors: yes

  - name: 実行結果（httpd停止）
    debug:
      msg: "{{ stop_process_result }}"

  - name: nginxの起動
    systemd:
      name: "{{ start_process }}"
      state: started
      enabled: yes
    ignore_errors: yes